spring:
  application:
    name: marketplace
  datasource:
    password: 1
    url: jdbc:postgresql://localhost:5432/waa-project
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
  profiles:
    active: private
server:
  port: 8080
